<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Back to products_inventory_details_img</name>
   <tag></tag>
   <elementGuidId>c5bf265c-3506-4f56-9efc-bbbe7259f564</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='inventory_item_container']/div/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.inventory_details_img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>6b29f448-a079-4372-854c-d253eb386218</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Sauce Labs Bike Light</value>
      <webElementGuid>c4df8ffd-1bf7-424a-a39d-42c4f61b2d1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inventory_details_img</value>
      <webElementGuid>651e1741-6d29-4f44-bb0b-6e97a773d1b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/static/media/bike-light-1200x1500.37c843b0.jpg</value>
      <webElementGuid>50f9ee50-c1c7-4497-9270-58de09bdedf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inventory_item_container&quot;)/div[@class=&quot;inventory_details&quot;]/div[@class=&quot;inventory_details_container&quot;]/div[@class=&quot;inventory_details_img_container&quot;]/img[@class=&quot;inventory_details_img&quot;]</value>
      <webElementGuid>5413e636-3563-45f5-b3b9-9f0b594a04c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='inventory_item_container']/div/div/div/img</value>
      <webElementGuid>41db3c9c-05b3-408c-8cfa-f1dc7f2eac20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Sauce Labs Bike Light']</value>
      <webElementGuid>e359318b-282d-4e15-9e30-c08bf41b367a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/img</value>
      <webElementGuid>e01c6d10-6bb4-4f3e-bb9d-19858e2367c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Sauce Labs Bike Light' and @src = '/static/media/bike-light-1200x1500.37c843b0.jpg']</value>
      <webElementGuid>76a010a9-cf2d-4ed1-88ba-acc922dbdc71</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
